import * as React from 'react';
import './goodreads.css';

export const Books = (props) => (
    <React.Fragment>
      <div id="gr_grid_widget_1614925633">
          <div class="gr_grid_container">
    <div class="gr_grid_book_container"><a title="Eragon (The Inheritance Cycle, #1)" rel="nofollow" href="https://www.goodreads.com/book/show/113436.Eragon"><img alt="Eragon" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1366212852l/113436._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Elantris (Elantris, #1)" rel="nofollow" href="https://www.goodreads.com/book/show/68427.Elantris"><img alt="Elantris" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1475740953l/68427._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="City of Bones (The Mortal Instruments, #1)" rel="nofollow" href="https://www.goodreads.com/book/show/256683.City_of_Bones"><img alt="City of Bones" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1432730315l/256683._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Hunger Games (The Hunger Games, #1)" rel="nofollow" href="https://www.goodreads.com/book/show/2767052-the-hunger-games"><img alt="The Hunger Games" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722975l/2767052._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Catching Fire (The Hunger Games, #2)" rel="nofollow" href="https://www.goodreads.com/book/show/6148028-catching-fire"><img alt="Catching Fire" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722941l/6148028._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Host" rel="nofollow" href="https://www.goodreads.com/book/show/1656001.The_Host"><img alt="The Host" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1318009171l/1656001._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Harry Potter and the Chamber of Secrets (Harry Potter, #2)" rel="nofollow" href="https://www.goodreads.com/book/show/15881.Harry_Potter_and_the_Chamber_of_Secrets"><img alt="Harry Potter and the Chamber of Secrets" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474169725l/15881._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Harry Potter and the Goblet of Fire (Harry Potter, #4)" rel="nofollow" href="https://www.goodreads.com/book/show/6.Harry_Potter_and_the_Goblet_of_Fire"><img alt="Harry Potter and the Goblet of Fire" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1554006152l/6._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)" rel="nofollow" href="https://www.goodreads.com/book/show/5.Harry_Potter_and_the_Prisoner_of_Azkaban"><img alt="Harry Potter and the Prisoner of Azkaban" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1499277281l/5._SY160_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Harry Potter and the Order of the Phoenix (Harry Potter, #5)" rel="nofollow" href="https://www.goodreads.com/book/show/2.Harry_Potter_and_the_Order_of_the_Phoenix"><img alt="Harry Potter and the Order of the Phoenix" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Harry Potter and the Half-Blood Prince (Harry Potter, #6)" rel="nofollow" href="https://www.goodreads.com/book/show/1.Harry_Potter_and_the_Half_Blood_Prince"><img alt="Harry Potter and the Half-Blood Prince" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1587697303l/1._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Harry Potter and the Sorcerer's Stone" rel="nofollow" href="https://www.goodreads.com/book/show/3.Harry_Potter_and_the_Sorcerer_s_Stone"><img alt="Harry Potter and the Sorcerer's Stone" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474154022l/3._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Hobbit, Part One" rel="nofollow" href="https://www.goodreads.com/book/show/17157681-the-hobbit-part-one"><img alt="The Hobbit, Part One" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1371834025l/17157681._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Harry Potter and the Deathly Hallows (Harry Potter, #7)" rel="nofollow" href="https://www.goodreads.com/book/show/136251.Harry_Potter_and_the_Deathly_Hallows"><img alt="Harry Potter and the Deathly Hallows" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474171184l/136251._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Fellowship of the Ring (The Lord of the Rings, #1)" rel="nofollow" href="https://www.goodreads.com/book/show/34.The_Fellowship_of_the_Ring"><img alt="The Fellowship of the Ring" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1298411339l/34._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Way of Kings (The Stormlight Archive, #1)" rel="nofollow" href="https://www.goodreads.com/book/show/7235533-the-way-of-kings"><img alt="The Way of Kings" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1388184640l/7235533._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Final Empire (Mistborn, #1)" rel="nofollow" href="https://www.goodreads.com/book/show/68428.The_Final_Empire"><img alt="The Final Empire" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1480717416l/68428._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Well of Ascension (Mistborn, #2)" rel="nofollow" href="https://www.goodreads.com/book/show/68429.The_Well_of_Ascension"><img alt="The Well of Ascension" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1480717596l/68429._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="The Hero of Ages (Mistborn, #3)" rel="nofollow" href="https://www.goodreads.com/book/show/2767793-the-hero-of-ages"><img alt="The Hero of Ages" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1480717763l/2767793._SX98_.jpg" /></a></div>
    <div class="gr_grid_book_container"><a title="Words of Radiance (The Stormlight Archive, #2)" rel="nofollow" href="https://www.goodreads.com/book/show/17332218-words-of-radiance"><img alt="Words of Radiance" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1507307927l/17332218._SX98_.jpg" /></a></div>
  <noscript><br/>Share <a rel="nofollow" href="/">book reviews</a> and ratings with Cameron, and even join a <a rel="nofollow" href="/group">book club</a> on Goodreads.</noscript>
  </div>

      </div>
      <script src="https://www.goodreads.com/review/grid_widget/110517573.Cameron's%20read%20book%20montage?cover_size=medium&hide_link=true&hide_title=true&num_books=200&order=a&shelf=read&sort=date_added&widget_id=1614925633" type="text/javascript" charset="utf-8"></script>

    </React.Fragment>
);
